version: '3'

services:
  backend:
    build: ./LITABA_BACKEND
    ports:
      - "8000:8000"
    volumes:
      - ./LITABA_BACKEND:/code
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    build: ./LITABA_FRONTEND
    ports:
      - "3000:3000"
    volumes:
      - ./LITABA_FRONTEND:/app
    depends_on:
      - backend
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env